service: inhafood-bot

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: ap-northeast-2

functions:
  keyboard:
    handler: handler.keyboard
    events:
      - http:
          path: keyboard
          method: get
  message:
    handler: handler.message
    events:
      - http:
          path: message
          method: post
